### ISSUE TITLE
Path issue on Linux (and probably Mac too) when first installed

### ISSUE THREAD

**Issue by jillalberts** [derwish-pro/obsidian-remember-cursor-position#2]
Hi, thank you for this extension, it will be very helpful when working on long documents!

When I first installed the extension it was dumping the save file right into the root folder of my vault with a very long filename. I realized that this is happening because in the plugin settings, the default filename is something like:

`.obsidian\plugins\obsidian-remember-cursor-position\cursor-positions.json`

This probably works fine on Windows, but Linux and Mac systems use a `/` rather than a `\` as a directory separator. Therefore  the cursor position gets saved in a file *in the root directory of the vault* that's **named** something like `.obsidian\plugins\obsidian-remember-cursor-position\cursor-positions.json`. (there was another file in there too that was the same name but with the backslashes url-encoded, but I don't know if that was because of the plugin or my use of Dropbox or something)

Changing all the backslashes to forward slashes in the plugin's settings makes it stash the file in the obsidian/plugins/[...] subfolder as expected (and then the oddly-named file in the root of the vault can be deleted)

Obviously this is not a huge issue, and the plugin itself still works, but it would be nicer if it saved correctly on Linux and Mac systems.

Thank you again for the plugin!

**Comment by derwish-pro** [comment]
Thank you for your feedback. I'll try to fix this as soon as I have time, but for now I'll add it to the readme.

**Comment by derwish-pro** [comment]
Fixed

**Comment by jillalberts** [comment]
Amazing! Thank you so much!
